export const Constants = {
  BASE_URL: process.env.REACT_APP_BASE_URL || "http://localhost:3005/",
  //BASE_URL: "http://13.57.247.65/",
  app_id: "5c3719c3742fbf5414968231",
  locationId: "",
  charge: 0,
  couponApplied: false,
  deductedPrice: 0
};

export const state = {
  Alabama: "AL",
  Alaska: "AK",
  Arizona: "AZ",
  Arkansas: "AR",
  California: "CA",
  Colorado: "CO",
  Connecticut: "CT",
  Delaware: "DE",
  Florida: "FL",
  Georgia: "GA",
  Hawaii: "HI",
  Idaho: "ID",
  Illinois: "IL",
  Indiana: "IN",
  Iowa: "IA",
  Kansas: "KS",
  Kentucky: "KY",
  Louisiana: "LA",
  Maine: "ME",
  Maryland: "MD",
  Massachusetts: "MA",
  Michigan: "MI",
  Minnesota: "MN",
  Mississippi: "MS",
  Missouri: "MO",
  Montana: "MT",
  Nebraska: "NE",
  Nevada: "NV",
  Hampshire: "NH",
  Jersey: "NJ",
  Mexico: "NM",
  New_York: "NY",
  North_Carolina: "NC",
  North_Dakota: "ND",
  Ohio: "OH",
  Oklahoma: "OK",
  Oregon: "OR",
  Pennsylvania: "PA",
  Rhode_Island: "RI",
  South_Carolina: "SC",
  South_Dakota: "SD",
  Tennessee: "TN",
  Texas: "TX",
  Utah: "UT",
  Vermont: "VT",
  Virginia: "VA",
  Washington: "WA",
  West_Virginia: "WV",
  Wisconsin: "WI",
  Wyoming: "WY"
};
